#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow", "cairosvg"]
# ///
"""mark-sheet.py — render every drawn mark as one contact sheet.

WHY THIS EXISTS, and it is not convenience.

Four drawings were rejected in a single session on RECOGNITION, not geometry:
a pen that read as a scalpel, a dividers pair whose symmetric arc closed into
a tent, a set of labelled dots that read as a bulleted list, and a three-cell
choropleth whose shading assembled into an isometric cube. Every one of them
was geometrically fine. None of those failures is visible in the source, and
none is findable by reasoning about path data -- they are only visible when
the thing is rendered at the size it will actually be seen at, and then looked
at.

PUBLISHING.md already says "render at 3-6x before believing it". That advice
was followed by hand-rebuilding the same scaffolding each time, which is
exactly the kind of instruction that gets skipped on the fifth icon. One
command is what turns it into a habit.

SIZE IS NOT A PARAMETER, which is the other reason this is a sheet and not a
single render. The site draws marks at three sizes -- nav icons 24x24 shown
near 17px, project marks 40x40, home-page figure marks 120x76 at 160px -- and
four of the shared keys were REDRAWN at each, not scaled, because the age
pyramid loses its bands and the relocation grid closes into a blob below about
80px. Detail budgets differ by a lot: three or four elements at 17px, six or
seven at 40px.

SCOPE is the project marks in _includes/project-mark.html only. The nav icons
and the figure marks are separate drawings in their own files. So the 17px
column here is a PREVIEW of how a project mark would fare at nav size, not the
nav icon itself, and the third column is a blow-up for judging rather than a
size the site draws at.

USAGE
  script/mark-sheet.py                     # every mark in _includes/project-mark.html
  script/mark-sheet.py --scale 6           # blow-ups for judging a new drawing
  script/mark-sheet.py --out /tmp/x.png
  script/mark-sheet.py --light             # check it survives a light ground too

Writes a PNG and prints the path. Nothing is committed by this script.
"""
from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

import cairosvg
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
MARKS = ROOT / "_includes" / "project-mark.html"

# Straight from lite.css. Copied rather than parsed: this script must keep
# working if the stylesheet is mid-edit, and a mark sheet that fails to render
# because the CSS is being changed is useless exactly when it is wanted.
INK = "#e8e8e8"
INK_2 = "#cbb8a9"
INK_FAINT = "#4a4038"
VOID = "#000000"
PAPER = "#ffffff"

# The sizes the site actually draws at. `label` is what to call it, `px` is the
# rendered size, and it is the RENDERED size that matters, not the viewBox.
# The third column is a BLOW-UP, not a size the site draws at. project-mark.html
# holds the 40x40 project marks only; the 120x76 home-page figure marks live in
# index.html and are separate drawings, not scalings of these. Labelling this
# "figure 160px" would have claimed a correspondence that does not exist.
SCALES = [("nav ~17px", 17), ("project 40px", 40), ("6x blow-up", 240)]


def extract_marks(path: Path) -> list[tuple[str, str]]:
    """[(key, svg)] from the Liquid case/when block.

    The include is a Liquid `case` whose branches each hold one <svg>. Parsing
    it with a regex is fine and deliberate: the file is generated by nobody,
    edited by hand, and has exactly one shape.
    """
    src = path.read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r'\{%\s*when\s+"([a-z-]+)"\s*%\}(.*?)(?=\{%\s*when|\{%\s*endcase)',
                         src, flags=re.S):
        key, body = m.group(1), m.group(2)
        svg = re.search(r"<svg\b.*?</svg>", body, flags=re.S)
        if svg:
            out.append((key, svg.group(0)))
    return out


def render(svg: str, px: int, fg: str, ground: str) -> Image.Image:
    """One mark at one size, on the ground it will really sit on.

    `currentColor` is what the marks use throughout, so it has to be resolved
    before rasterising -- cairosvg has no notion of an inherited text colour.
    var(--ink-faint) appears in the grid strokes of some marks and is likewise
    substituted here rather than left to fail silently to black-on-black.
    """
    s = svg.replace("currentColor", fg)
    s = re.sub(r"var\(--ink-faint[^)]*\)", INK_FAINT, s)
    s = re.sub(r"var\(--ink-2[^)]*\)", INK_2, s)
    s = re.sub(r"var\(--[a-z0-9-]+\)", fg, s)      # anything left over
    png = cairosvg.svg2png(bytestring=s.encode("utf-8"),
                           output_width=px, output_height=px,
                           background_color=ground)
    return Image.open(io.BytesIO(png)).convert("RGB")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scale", type=float, default=1.0,
                    help="multiply every size (PUBLISHING.md says 3-6x when judging)")
    ap.add_argument("--light", action="store_true",
                    help="render on white instead of the site's black")
    ap.add_argument("--out", default=str(ROOT / "_site" / "mark-sheet.png"))
    args = ap.parse_args()

    if not MARKS.exists():
        print(f"no {MARKS}", file=sys.stderr)
        return 2
    marks = extract_marks(MARKS)
    if not marks:
        # A silent empty sheet is the failure this project keeps re-learning:
        # a check that matches nothing looks exactly like a check that passes.
        print(f"NO MARKS PARSED out of {MARKS} — the include's shape changed",
              file=sys.stderr)
        return 1

    ground = PAPER if args.light else VOID
    fg = "#1a1a1a" if args.light else INK
    label_col = "#555555" if args.light else INK_2

    sizes = [(lab, max(8, round(px * args.scale))) for lab, px in SCALES]
    pad, gutter, header, rowlab = 26, 34, 30, 108
    col_w = [px for _, px in sizes]
    sheet_w = rowlab + sum(col_w) + gutter * len(sizes) + pad * 2
    row_h = max(px for _, px in sizes) + gutter
    sheet_h = header + pad + row_h * len(marks) + pad

    sheet = Image.new("RGB", (sheet_w, sheet_h), ground)
    d = ImageDraw.Draw(sheet)

    x = pad + rowlab
    for (lab, px) in sizes:
        d.text((x, pad), f"{lab}", fill=label_col)
        x += px + gutter

    y = header + pad
    for key, svg in marks:
        d.text((pad, y + row_h // 2 - 6), key, fill=fg)
        x = pad + rowlab
        for (_lab, px) in sizes:
            try:
                img = render(svg, px, fg, ground)
                sheet.paste(img, (x, y + (row_h - gutter - px) // 2 + gutter // 2))
            except Exception as e:
                d.text((x, y + 10), f"ERR {e}"[:24], fill="#e04a42")
            x += px + gutter
        d.line([(pad, y + row_h - 4), (sheet_w - pad, y + row_h - 4)], fill=INK_FAINT)
        y += row_h

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out)
    print(f"{len(marks)} marks x {len(sizes)} sizes -> {out}")
    print("  " + ", ".join(k for k, _ in marks))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
